# Generated by Django 4.2.5 on 2023-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Жанр")),
                (
                    "discription",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PublishingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Издательство")),
                (
                    "discription",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Издательство",
                "verbose_name_plural": "Издательства",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Серия")),
                (
                    "discription",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Серию",
                "verbose_name_plural": "Серии",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автора",
                "verbose_name_plural": "Авторы",
                "ordering": ("last_name",),
            },
        ),
    ]
