# Generated by Django 4.2.5 on 2023-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="writer",
            options={
                "ordering": ("name",),
                "verbose_name": "Автора",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.RemoveField(
            model_name="writer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="writer",
            name="name",
            field=models.CharField(default=1, max_length=100, verbose_name="Автор"),
            preserve_default=False,
        ),
    ]
