# Generated by Django 4.2.5 on 2023-10-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0002_alter_writer_options_remove_writer_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="writer",
            name="discription",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Описание"
            ),
        ),
    ]
