# Generated by Django 4.2.5 on 2023-10-01 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_of_the_book",
                    models.CharField(max_length=50, verbose_name="Название книги"),
                ),
                (
                    "cover_foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=None,
                        verbose_name="Фото обложки",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Цена(BYN)"
                    ),
                ),
                (
                    "year_of_publication",
                    models.IntegerField(verbose_name="Год издания"),
                ),
                ("page", models.IntegerField(verbose_name="Количество страниц")),
                ("binding", models.CharField(max_length=50, verbose_name="Переплёт")),
                ("format", models.CharField(max_length=50, verbose_name="Формат")),
                (
                    "isbn",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                        verbose_name="ISBN",
                    ),
                ),
                ("weight", models.IntegerField(verbose_name="Вес(гр)")),
                ("age", models.IntegerField(verbose_name="Возрастные ограничения")),
                (
                    "availability",
                    models.IntegerField(verbose_name="Количество книг в наличии"),
                ),
                (
                    "active",
                    models.CharField(
                        choices=[("Да", "ДА"), ("Нет", "НЕТ")],
                        default="Да",
                        max_length=3,
                        verbose_name="Активный(Доступен для заказа Да/Нет)",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Рейтинг(1-10)",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата внесения в каталог"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения карточки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublishingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Издательство")),
                ("discription", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Серия")),
            ],
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "book",
                    models.ManyToManyField(
                        related_name="writer_of_book", to="catalog.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Жанр")),
                ("discription", models.TextField(max_length=300)),
                (
                    "book",
                    models.ManyToManyField(
                        related_name="genre_of_book", to="catalog.book"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                related_name="book_of_writer", to="catalog.genre"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publishing_house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.publishinghouse",
                verbose_name="Издательство",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="writer",
            field=models.ManyToManyField(
                related_name="book_of_writer", to="catalog.writer"
            ),
        ),
    ]
