# Generated by Django 4.2.5 on 2023-10-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="book_images/%Y/%m/%d",
                verbose_name="Фото обложки",
            ),
        ),
    ]
