# Generated by Django 4.2.5 on 2023-10-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="serie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.serie",
                verbose_name="Серия",
            ),
            preserve_default=False,
        ),
    ]
