# Generated by Django 4.2.5 on 2023-10-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0003_writer_discription"),
        ("catalog", "0002_alter_book_cover_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                related_name="book_of_genre", to="guide.genre", verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishing_house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book_of_ublishing_house",
                to="guide.publishinghouse",
                verbose_name="Издательство",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="book_of_serie",
                to="guide.serie",
                verbose_name="Серия",
            ),
        ),
    ]
