# Generated by Django 4.2.5 on 2023-10-01 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_book_serie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="book",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
