# Generated by Django 4.2.5 on 2023-10-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0005_delete_onetomany"),
        ("catalog", "0003_alter_book_genre_alter_book_publishing_house_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                related_name="books", to="guide.genre", verbose_name="Жанр"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishing_house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to="guide.publishinghouse",
                verbose_name="Издательство",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to="guide.serie",
                verbose_name="Серия",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="writer",
            field=models.ManyToManyField(
                related_name="books", to="guide.writer", verbose_name="Автор"
            ),
        ),
    ]
