# Generated by Django 4.2.5 on 2023-10-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_book_genre_alter_book_publishing_house_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_foto",
            field=models.ImageField(
                default=1, upload_to="book_images/%Y/%m/%d", verbose_name="Фото обложки"
            ),
            preserve_default=False,
        ),
    ]
