# Generated by Django 4.2.5 on 2023-10-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_book_cover_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="binding",
            field=models.CharField(max_length=100, verbose_name="Переплёт"),
        ),
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(max_length=100, verbose_name="Формат"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_of_the_book",
            field=models.CharField(max_length=100, verbose_name="Название книги"),
        ),
    ]
