# Generated by Django 4.2.5 on 2023-10-29 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("-publish",),
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
    ]
