# Generated by Django 4.2.5 on 2023-10-29 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_book_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("-publish",),
                "verbose_name": "Книга",
                "verbose_name_plural": "Книгу",
            },
        ),
    ]
