# Generated by Django 4.2.5 on 2023-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_productincart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_adress",
            field=models.TextField(verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=13, verbose_name="Телефон"),
        ),
    ]
