# Generated by Django 4.2.5 on 2023-10-21 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_productcart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзину", "verbose_name_plural": "Корзины"},
        ),
    ]
