# Generated by Django 4.2.5 on 2023-10-21 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата внесения"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=3000, verbose_name="Комментарий"),
        ),
    ]
