# Generated by Django 4.2.5 on 2023-10-21 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_comment_created_alter_comment_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created",
        ),
    ]
